// Generated by export_mobilenet_qspi.py; see the template README.
#ifndef PROJECT_NCNN_MOBILENET_MANIFEST_H_
#define PROJECT_NCNN_MOBILENET_MANIFEST_H_
#include <stdint.h>
namespace mobilenet_fixture {
constexpr uintptr_t kQspiBase = 0x90500000u;
constexpr uint32_t kImageHeader[16] = {
	0x33564e4du,
	0x00000001u,
	0x009afb00u,
	0x00000040u,
	0x00002450u,
	0x00002490u,
	0x009ad670u,
	0x95de5ccau,
	0xcd11bbe1u,
	0x00000060u,
	0x00000000u,
	0x00000098u,
	0x2ffe3b0eu,
	0x149e7902u,
	0x000000d8u,
	0x00000000u
};
} // namespace mobilenet_fixture
#endif
