#!/usr/bin/env python3
"""Export the fixed cat2.jpg fixture and native 224x224 MobileNet reference."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import zlib

JPEG_SHA256 = "a5e283094ee97c0acbff965fc4def7e896f5c1e7ce33ae3c1629aa7d20b49f75"
MODEL_SHA256 = {
    "model.param.bin": "fc24f1ad7b7c4d2c9eaf938bcd6db9b341a4076470d45e436255683c9c2f6347",
    "model.bin": "64ec37d2d7fd0b8135f6b865863293768136a90e51f9dea14b971f945b5eb90e",
    "model-fp32.bin": "44554404eb8d7da64f0b98142482ff186d0721df0977abcf43823e13da0ad473",
}


def header(guard, body):
    return ("// Generated by export_mobilenet_photo.py; see README.\n"
            f"#ifndef {guard}\n#define {guard}\n#include <stdint.h>\n"
            "namespace mobilenet_photo_fixture {\n" + body + "\n}\n#endif\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runner", type=Path, required=True)
    parser.add_argument("--model-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    jpeg_path = Path(__file__).resolve().parents[1] / "data_samples/photos/cat2.jpg"
    jpeg = jpeg_path.read_bytes()
    if hashlib.sha256(jpeg).hexdigest() != JPEG_SHA256:
        raise ValueError("source photograph changed; review fixture explicitly")
    for name, digest in MODEL_SHA256.items():
        if hashlib.sha256((args.model_dir / name).read_bytes()).hexdigest() != digest:
            raise ValueError("unexpected model: " + name)
    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    subprocess.run([str(args.runner.resolve()), str(args.model_dir.resolve()), str(jpeg_path), str(out.resolve())], check=True)
    rgb = (out / "decoded.rgb").read_bytes()
    tensor = (out / "input-fp32.bin").read_bytes()
    reference = (out / "reference-fp32.bin").read_bytes()
    if len(rgb) != 295 * 231 * 3 or len(tensor) != 224 * 224 * 3 * 4 or len(reference) != 4000:
        raise ValueError("unexpected decoded/input/output size")
    rows = [", ".join(f"0x{x:02x}" for x in jpeg[i:i+16]) for i in range(0, len(jpeg), 16)]
    (out / "photo_jpeg.h").write_text(header("PROJECT_NCNN_PHOTO_JPEG_H_",
        "constexpr unsigned char kJpeg[] = {\n" + ",\n".join(rows) + "\n};"))
    floats = struct.unpack("<1000f", reference)
    rows = [" ".join(f"{x:.9e}f," for x in floats[i:i+5]) for i in range(0, 1000, 5)]
    body = (f"constexpr uint32_t kJpegCrc = 0x{zlib.crc32(jpeg):08x}u;\n"
            f"constexpr uint32_t kRgbCrc = 0x{zlib.crc32(rgb):08x}u;\n"
            f"constexpr uint32_t kInputCrc = 0x{zlib.crc32(tensor):08x}u;\n"
            "constexpr float kReference[1000] = {\n" + "\n".join(rows) + "\n};")
    (out / "photo_reference.h").write_text(header("PROJECT_NCNN_PHOTO_REFERENCE_H_", body))
    blobs = {"jpeg": jpeg, "decoded_rgb": rgb, "input_fp32": tensor, "reference_fp32": reference}
    metadata = {"source": "project/ncnn/data_samples/photos/cat2.jpg", "source_size": [295, 231],
                "input_size": [224, 224], "preprocessing": "scalar stb JPEG RGB; NCNN bilinear square resize; multiply 1/255; mean/std inside graph",
                "model_sha256": MODEL_SHA256,
                "blobs": {k: {"bytes": len(v), "sha256": hashlib.sha256(v).hexdigest(), "crc32": f"{zlib.crc32(v):08x}"} for k, v in blobs.items()}}
    (out / "photo-manifest.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
