#!/usr/bin/env python3
"""Package the repository's fixed MobileNetV3-Small fixture for STM32 QSPI."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct
import subprocess
import zlib

EXPECTED = {
    "model.param.bin": "fc24f1ad7b7c4d2c9eaf938bcd6db9b341a4076470d45e436255683c9c2f6347",
    "model.bin": "64ec37d2d7fd0b8135f6b865863293768136a90e51f9dea14b971f945b5eb90e",
}
FLASH_OFFSET = 0x500000
CONV_OFFSET = 0xFF0000


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--converter", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--source-header", type=Path, default=Path(__file__).resolve().parents[1]
                        / "models/mobilenetv3_small/assets/mobilenetv3_small.mem.h")
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    source = args.source_header.read_text()
    blobs = {}
    for name, body in re.findall(r"static const unsigned char (\w+)\[\] = \{(.*?)\};", source, re.S):
        data = bytes(int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})", body))
        filename = "model.param.bin" if "param" in name else "model.bin"
        if filename in blobs or hashlib.sha256(data).hexdigest() != EXPECTED[filename]:
            raise ValueError("unexpected source model; regenerate/review fixture explicitly")
        blobs[filename] = data
        (args.output_dir / filename).write_bytes(data)
    if set(blobs) != set(EXPECTED):
        raise ValueError("missing source model arrays")
    subprocess.run([str(args.converter.resolve()), str(args.output_dir.resolve())], check=True)
    param = blobs["model.param.bin"]
    model = (args.output_dir / "model-fp32.bin").read_bytes()
    reference = (args.output_dir / "reference-fp32.bin").read_bytes()
    conversion = json.loads((args.output_dir / "conversion.json").read_text())
    if len(param) != 9296 or len(model) != 10147440 or len(reference) != 4000:
        raise ValueError("unexpected converted model/reference size")
    model_offset = (64 + len(param) + 15) & ~15
    total = model_offset + len(model)
    sector_count = (total + 65535) // 65536
    if FLASH_OFFSET + sector_count * 65536 > CONV_OFFSET:
        raise ValueError("image would overlap convolution fixture")
    header = [0x33564E4D, 1, total, 64, len(param), model_offset, len(model),
              zlib.crc32(param), zlib.crc32(model), 96, 0, 152,
              zlib.crc32(reference), zlib.crc32(blobs["model.bin"]),
              conversion["tagged_blobs"] * 4, 0]
    image = bytearray(b"\xff" * total)
    image[:64] = struct.pack("<16I", *header)
    image[64:64 + len(param)] = param
    image[model_offset:] = model
    (args.output_dir / "mobilenet-qspi.bin").write_bytes(image)
    words = ",\n\t".join(f"0x{x:08x}u" for x in header)
    (args.output_dir / "manifest.h").write_text(
        "// Generated by export_mobilenet_qspi.py; see the template README.\n"
        "#ifndef PROJECT_NCNN_MOBILENET_MANIFEST_H_\n#define PROJECT_NCNN_MOBILENET_MANIFEST_H_\n"
        "#include <stdint.h>\nnamespace mobilenet_fixture {\n"
        "constexpr uintptr_t kQspiBase = 0x90500000u;\n"
        f"constexpr uint32_t kImageHeader[16] = {{\n\t{words}\n}};\n"
        "} // namespace mobilenet_fixture\n#endif\n")
    metadata = {"source_sha256": EXPECTED, "conversion": conversion,
                "input": "RGB: ((3*x + 5*y + 17*channel) % 256) / 255, 96x96; normalization in graph",
                "flash_offset": hex(FLASH_OFFSET), "first_sector": FLASH_OFFSET // 65536,
                "last_sector": FLASH_OFFSET // 65536 + sector_count - 1,
                "image_bytes": len(image), "param_bytes": len(param), "fp32_model_bytes": len(model),
                "header": header,
                "image_sha256": hashlib.sha256(image).hexdigest(),
                "fp32_model_sha256": hashlib.sha256(model).hexdigest(),
                "reference_sha256": hashlib.sha256(reference).hexdigest()}
    (args.output_dir / "manifest.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
